### ISSUE TITLE
Some suggestions about this project

### ISSUE THREAD

**Issue by MoYuan-CN** [RedstoneCraftTeam/rscraft-site#1]
1. what the hell is this layout? why? why it layouted in column mode?
![image](https://github.com/RedstoneCraftTeam/rscraft-site/assets/109946426/d26789d5-7aed-4460-85db-09467352bd8b)
2. using parentheses in parentheses doesn't look good
![image](https://github.com/RedstoneCraftTeam/rscraft-site/assets/109946426/1097dcd7-bea4-45a4-953b-b6ea67483582)
3. use knock off and tick to show vulnerability is not a good idea
better choose is use vulnerability level words like `Low` `Moderate` and so on.
4. authentication your account in donate platform. or else we can't see anything about project before donate (at donate page)

**Comment by gene-2012** [comment]
Thank you very much for your suggestion. We are working hard to fix it :-)
